-- 009_resolution_plans.sql: AI Resolution Agent (#3) plan store.
--
-- Resolution plans are generated by the AI resolution agent, held for human
-- approval, and executed only through an allowlisted action set.

CREATE TABLE IF NOT EXISTS resolution_plans (
  id bigserial PRIMARY KEY,
  tenant_id integer REFERENCES tenants(id) ON DELETE CASCADE,
  ticket_id integer NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  analysis_id bigint REFERENCES ai_analyses(id) ON DELETE SET NULL,
  steps jsonb NOT NULL DEFAULT '[]'::jsonb,
  actions jsonb NOT NULL DEFAULT '[]'::jsonb,
  confidence numeric(5,2),
  sources jsonb NOT NULL DEFAULT '[]'::jsonb,
  recommended_action text,
  requires_approval boolean NOT NULL DEFAULT true,
  risk_level text NOT NULL DEFAULT 'low',
  status text NOT NULL DEFAULT 'proposed', -- proposed|approved|rejected|executed
  decided_by_id integer,
  decided_at timestamptz,
  decision_note text,
  executed_at timestamptz,
  execution_log jsonb,
  created_by_id integer,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS resolution_plans_ticket ON resolution_plans(ticket_id, created_at DESC);
-- Backfill decision_note if the table predates it.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'resolution_plans' AND column_name = 'decision_note'
  ) THEN
    ALTER TABLE resolution_plans ADD COLUMN decision_note text;
  END IF;
END $$;
