import assistantRouter from "./assistant.js";
import workspaceSettingsRouter from "./workspaceSettings.js";
import { Router } from "express";
import operationsRouter from "./operations.js";
import automationRulesRouter from "./automationRules.js";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import ticketsRouter from "./tickets.js";
import departmentsRouter from "./departments.js";
import dashboardRouter from "./dashboard.js";
import emailRouter from "./email.js";
import permissionsRouter from "./permissions.js";
import settingsRouter from "./settings.js";
import publicRequestRouter from "./publicRequest.js";
import attachmentsRouter from "./attachments.js";
import emailAccountsRouter from "./emailAccounts.js";
import webhooksRouter from "./webhooks.js";
import cronRouter from "./cron.js";

import verificationIntakeRouter from "./verificationIntake.js";
const router = Router();
router.use(verificationIntakeRouter);

router.use(healthRouter);
router.use(automationRulesRouter);
router.use(operationsRouter);
router.use(publicRequestRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(ticketsRouter);
router.use(departmentsRouter);
router.use(dashboardRouter);
router.use(emailRouter);
router.use(permissionsRouter);
router.use(settingsRouter);
router.use(attachmentsRouter);
router.use(emailAccountsRouter);
router.use("/webhooks", webhooksRouter);
router.use(cronRouter);

router.use(workspaceSettingsRouter);
router.use(assistantRouter);
export default router;
