import aiWorkforceRouter from "./aiWorkforce.js";
import assistantRouter from "./assistant.js";
import workspaceSettingsRouter from "./workspaceSettings.js";
import { Router } from "express";
import operationsRouter from "./operations.js";
import automationRulesRouter from "./automationRules.js";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import ticketsRouter from "./tickets.js";
import departmentsRouter from "./departments.js";
import dashboardRouter from "./dashboard.js";
import emailRouter from "./email.js";
import permissionsRouter from "./permissions.js";
import settingsRouter from "./settings.js";
import publicRequestRouter from "./publicRequest.js";
import attachmentsRouter from "./attachments.js";
import emailAccountsRouter from "./emailAccounts.js";
import webhooksRouter from "./webhooks.js";
import cronRouter from "./cron.js";
import migrationsRouter from "./migrations.js";
import slaRouter from "./sla.js";

import verificationIntakeRouter from "./verificationIntake.js";
import briefsRouter from "./briefs.js";
import healthServicesRouter from "./health-services.js";
import forecastRouter from "./forecast.js";
import commandCenterRouter from "./command-center.js";
import adminCopilotRouter from "./admin-copilot.js";
import automationCopilotRouter from "./automation-copilot.js";
import catalogRouter from "./catalog.js";
import knowledgeRouter from "./knowledge.js";
import memoryRouter from "./memory.js";
import graphRouter from "./graph.js";
import agentAssistRouter from "./agent-assist.js";
import queueRouter from "./queue.js";
import intelligenceRouter from "./intelligence.js";
import changesRouter from "./changes.js";
import customersRouter from "./customers.js";
import operationsMapRouter from "./operations-map.js";
import swarmRouter from "./swarm.js";
import incidentsRouter from "./incidents.js";
import runbooksRouter from "./runbooks.js";
import monitoringRouter from "./monitoring.js";
import risksRouter from "./risks.js";
import rootCauseRouter from "./rootCause.js";
import resolutionRouter from "./resolution.js";
const router = Router();
router.use(verificationIntakeRouter);
router.use(swarmRouter);
router.use(incidentsRouter);
router.use(runbooksRouter);
router.use(intelligenceRouter);
router.use(changesRouter);
router.use(customersRouter);
router.use(operationsMapRouter);
router.use("/monitoring", monitoringRouter);

router.use(healthRouter);
router.use(automationRulesRouter);
router.use(operationsRouter);
router.use(publicRequestRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(ticketsRouter);
router.use(departmentsRouter);
router.use(dashboardRouter);
router.use(emailRouter);
router.use(permissionsRouter);
router.use(settingsRouter);
router.use(attachmentsRouter);
router.use(emailAccountsRouter);
router.use("/webhooks", webhooksRouter);
router.use("/graph", graphRouter);
router.use(cronRouter);
router.use(slaRouter);

router.use(workspaceSettingsRouter);
router.use(assistantRouter);
router.use(aiWorkforceRouter);
router.use(briefsRouter);
router.use(healthServicesRouter);
router.use(forecastRouter);
router.use(commandCenterRouter);
router.use(adminCopilotRouter);
router.use(automationCopilotRouter);
router.use(catalogRouter);
router.use(knowledgeRouter);
router.use(memoryRouter);
router.use(agentAssistRouter);
router.use(queueRouter);
router.use(risksRouter);
router.use(rootCauseRouter);
router.use(resolutionRouter);
router.use("/admin/migrations", migrationsRouter);
export default router;
